name: langbuddy_language_learning_application
description: A Flutter language learning helper app with no login
publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Text-to-Speech
  flutter_tts: ^3.8.0

  # Local storage (offline progress)
  shared_preferences: ^2.1.1

  # iOS style icons (required by Flutter)
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/langbuddy_logo.png

